name: Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache-dependency-path: go.sum
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release --clean
    - name: Upload assets
      uses: actions/upload-artifact@v3
      with:
        name: myapp
        path: dist/*
